site_name: Compliance Customer Experience Engineering (CxE)
repo_url: https://github.com/microsoft/ComplianceCxE
repo_name: microsoft/ComplianceCxE
edit_uri: https://github.com/microsoft/ComplianceCxE/edit/public/docs
nav:
    - OSS: 
      - One Stop Shop: index.md
      - Advanced eDiscovery: resources/aed.md
      - Microsoft Information Governance (MIG): resources/mig.md
      - Microsoft Information Protection (MIP): resources/mip.md
      - Data Loss Prevention (DLP): resources/dlp.md
      - Insider Risk Management (IR): resources/ir.md
      - Compliance Manager (CM): resources/cm.md
    #- Notes from the Field:
      #- Compliance Manager: notes/cm.md
      #- Advanced eDiscovery: notes/aed.md
      #- Advanced Audit: notes/audit.md
      #- Insider Risk: notes/ir.md
      #- Communication Compliance: notes/cc.md
      #- Information Governance: 
        #- Multi-stage: notes/mig/ms.md
        #- Adaptive Scopes: notes/mig/adpscp.md
      #- Records Management: notes/rm.md
      #- Information Protection: notes/mip.md
      #- Data Loss Prevention: notes/dlp.md
    - DAGs:
      - Getting Started: dag.md
      - Compliance Manager: dag/cm.md
      - Microsoft Compliance Configuration Analyzer (MCCA): dag/mcca.md
      - Adanced eDiscovery and Advanced Audit: dag/aed-audit.md
      - Insider Risk Management and Communication Compliance: dag/ir-cc.md
      - Microsoft Information Governance and Records Management: dag/mig-rm.md
      - Microsoft Information Protection and Data Loss Prevention: dag/mip-dlp.md
      - Resources: dag/dag-resources.md
    #- PowerShell: 
      #- Compliance Manager: powershell/cm.md
      #- Advanced eDiscovery: powershell/aed.md
      #- Advanced Audit: powershell/audit.md
      #- Insider Risk: powershell/ir.md
      #- Communication Compliance: powershell/cc.md
      #- Information Governance: powershell/mig.md
      #- Records Management: powershell/rm.md
      #- Information Protection: powershell/mip.md
      #- Data Loss Prevention: powershell/dlp.md
    - Playbooks:
      - Exchange ETR to DLP Playbook: playbooks/etr2dlp.md
      - Teams DLP Playbook: playbooks/teamsdlp.md
    - End User Training:
      - Sensitivity Labels: enduser\sensitivity.md
      - Retention Labels: enduser\retention.md
    - Webinars: webinars.md
    - Previews: previews.md
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  logo: img\scm-shield.png
  favicon: img\scm-shield.png
  features:
    - navigation.expand
    - navigation.top
    - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/microsoft/ComplianceCxE/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MIPNews
    - icon: fontawesome/brands/yammer
      link: https://aka.ms/MIPC/AskMIPTeam
extra_css:
  - assets/extra.css
extra_javascript:
  - scripts/extlinks.js
markdown_extensions:
  - toc:
      permalink: ⚓︎
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search